apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo123 
  description: Secure Supply Chain Example for Quarkus Java example with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    argocd/app-name: demo123
    janus-idp.io/tekton: demo123 
    backstage.io/kubernetes-id: demo123
    backstage.io/kubernetes-namespace: demo123
    backstage.io/techdocs-ref: dir:. 
  tags: ["java", "quarkus", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 